# Generated by Django 5.1.1 on 2024-10-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCodes',
            fields=[
                ('department_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department_codes',
            },
        ),
        migrations.CreateModel(
            name='FederalStates',
            fields=[
                ('federal_state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'federal_states',
            },
        ),
        migrations.CreateModel(
            name='HospitalLocations',
            fields=[
                ('hospital_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('street', models.CharField(blank=True, max_length=191, null=True)),
                ('city', models.CharField(blank=True, max_length=191, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=191, null=True)),
                ('mail', models.CharField(blank=True, max_length=191, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=14, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('link', models.CharField(blank=True, max_length=191, null=True)),
                ('federal_state_code', models.ForeignKey(blank=True, db_column='federal_state_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.federalstates')),
            ],
            options={
                'db_table': 'hospital_locations',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='ProviderTypeCodes',
            fields=[
                ('provider_type_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provider_type_codes',
            },
        ),
        migrations.CreateModel(
            name='TreatmentCodes',
            fields=[
                ('treatment_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'treatment_codes',
            },
        ),
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('hospital', models.OneToOneField(blank=True, default='123456', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.hospitallocations')),
                ('total_treatments', models.IntegerField(blank=True, null=True)),
                ('nursing_quotient', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nursing_count', models.IntegerField(blank=True, null=True)),
                ('bed_count', models.IntegerField(blank=True, null=True)),
                ('semi_residential_count', models.IntegerField(blank=True, null=True)),
                ('total_stations_count', models.IntegerField(blank=True, null=True)),
                ('has_emergency_service', models.IntegerField(blank=True, null=True)),
                ('emergency_service_level', models.IntegerField(blank=True, null=True)),
                ('provider_type_code', models.ForeignKey(blank=True, db_column='provider_type_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.providertypecodes')),
            ],
            options={
                'db_table': 'hospital_details',
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_count', models.IntegerField(blank=True, null=True)),
                ('department_code', models.ForeignKey(blank=True, db_column='department_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.departmentcodes')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hospitallocations')),
            ],
            options={
                'db_table': 'hospital_departments',
                'unique_together': {('hospital', 'department_code')},
            },
        ),
        migrations.CreateModel(
            name='HospitalCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(blank=True, max_length=191, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hospitallocations')),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
            ],
            options={
                'db_table': 'hospital_certificates',
                'unique_together': {('hospital', 'certificate', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='FederalStatesDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_state_name', models.CharField(blank=True, max_length=191, null=True)),
                ('federal_state_code', models.ForeignKey(blank=True, db_column='federal_state_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.federalstates')),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
            ],
            options={
                'db_table': 'federal_states_dict',
                'unique_together': {('federal_state_code', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentsDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_department_code', models.CharField(blank=True, max_length=4, null=True)),
                ('department_name', models.CharField(blank=True, max_length=191, null=True)),
                ('parent_department_name', models.CharField(blank=True, max_length=191, null=True)),
                ('department_code', models.ForeignKey(blank=True, db_column='department_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.departmentcodes')),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
            ],
            options={
                'db_table': 'departments_dict',
                'unique_together': {('department_code', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('city_district', models.CharField(blank=True, max_length=191, null=True)),
                ('rural_district', models.CharField(blank=True, max_length=191, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('federal_state_code', models.ForeignKey(blank=True, db_column='federal_state_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.federalstates')),
            ],
            options={
                'db_table': 'places',
                'unique_together': {('name', 'city_district', 'rural_district', 'zip', 'federal_state_code')},
            },
        ),
        migrations.CreateModel(
            name='ProviderTypesDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
                ('provider_type_code', models.ForeignKey(blank=True, db_column='provider_type_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.providertypecodes')),
            ],
            options={
                'db_table': 'provider_types_dict',
                'unique_together': {('provider_type_code', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='HospitalTreatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_count', models.IntegerField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hospitallocations')),
                ('treatment_code', models.ForeignKey(blank=True, db_column='treatment_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.treatmentcodes')),
            ],
            options={
                'db_table': 'hospital_treatments',
                'unique_together': {('hospital', 'treatment_code')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentsDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(blank=True, max_length=191, null=True)),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
                ('treatment_code', models.ForeignKey(blank=True, db_column='treatment_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.treatmentcodes')),
            ],
            options={
                'db_table': 'treatments_dict',
                'unique_together': {('treatment_code', 'language_code')},
            },
        ),
    ]
